### ISSUE TITLE
unmatched character in polybar

### ISSUE THREAD

**Issue by simex05** [Drish-xD/dotfiles#2]
Hi, i have this problem.

polybar|notice:  Loading module 'space' of type 'custom/text'
polybar|notice:  Loading module 'wlan' of type 'internal/network'
polybar|error: Disabling module "wlan" (reason: Invalid network interface "wlan0")
polybar|notice:  Loading module 'space' of type 'custom/text'
polybar|notice:  Loading module 'battery' of type 'internal/battery'
polybar|error: Disabling module "battery" (reason: No suitable way to get current charge state)
polybar|notice:  Loading module 'r1' of type 'custom/text'
polybar|notice:  Loading module 'gap' of type 'custom/text'
polybar|notice:  Loading module 'l1' of type 'custom/text'
polybar|notice:  Loading module 'date' of type 'internal/date'
polybar|notice:  Loading module 'r1' of type 'custom/text'
polybar|notice:  Loading module 'gap' of type 'custom/text'
polybar|notice:  Loaded 26 modules
polybar|notice:  Loaded font "JetBrainsMono Nerd Font Mono:style:bold:size=10" (name=Noto Sans, offset=2, file=/usr/share/fonts/noto/NotoSans-Bold.ttf)
polybar|notice:  Loaded font "JetBrainsMono Nerd Font Mono:size=20" (name=Noto Sans, offset=5, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
polybar|notice:  Loaded font "feather:style=Regular:size=12" (name=feather, offset=2, file=/usr/share/fonts/TTF/Feather.ttf)
polybar|warn:  Dropping unmatched character  (U+f303) in '  '
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e795) in ''
polybar|warn:  Dropping unmatched character  (U+f268) in ''
polybar|warn:  Dropping unmatched character  (U+e70c) in ''
polybar|warn:  Dropping unmatched character  (U+f1bc) in ''
polybar|warn:  Dropping unmatched character  (U+f215) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character 玲 (U+f9ad) in '玲 '
polybar|warn:  Dropping unmatched character  (U+f8e3) in ' '
polybar|warn:  Dropping unmatched character 怜 (U+f9ac) in '怜 '
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+f303) in '  '
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e795) in ''
polybar|warn:  Dropping unmatched character  (U+f268) in ''
polybar|warn:  Dropping unmatched character  (U+e70c) in ''
polybar|warn:  Dropping unmatched character  (U+f1bc) in ''
polybar|warn:  Dropping unmatched character  (U+f215) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character 玲 (U+f9ad) in '玲 '
polybar|warn:  Dropping unmatched character  (U+f8e3) in ' '
polybar|warn:  Dropping unmatched character 怜 (U+f9ac) in '怜 '
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+f303) in '  '
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e795) in ''
polybar|warn:  Dropping unmatched character  (U+f268) in ''
polybar|warn:  Dropping unmatched character  (U+e70c) in ''
polybar|warn:  Dropping unmatched character  (U+f1bc) in ''
polybar|warn:  Dropping unmatched character  (U+f215) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character 玲 (U+f9ad) in '玲 '
polybar|warn:  Dropping unmatched character  (U+f8e3) in ' '
polybar|warn:  Dropping unmatched character 怜 (U+f9ac) in '怜 '
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''
polybar|warn:  Dropping unmatched character  (U+e0b6) in ''
polybar|warn:  Dropping unmatched character  (U+e0b4) in ''

I think it is caused by feather font, but i have no idea to fix it
How can i solve?

**Comment by thequantumcog** [comment]
This is because the font is not correctly installed
